version: '3.9'
services:
    nginx:
        image: nginx:stable
        restart: always
        ports:
            - 8000:80
        depends_on:
            - shop
        volumes:
            - shop:/var/www/html
            - ./.ci/nginx.conf:/etc/nginx/conf.d/default.conf

    shop:
        image: a3dmorteza/laravel-ecommerce-example
        restart: always
        env_file:
            - .env
        depends_on:
            - shop-db
        volumes:
            - shop:/var/www/html
            - ./.ci/fpm.conf:/usr/local/etc/php-fpm.d/zz-custom.conf
            - ./app:/var/www/html/app
            - ./docker-entrypoint.sh:/docker-entrypoint.sh
    shop-db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root-secret
            - MYSQL_DATABASE=shop_db
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user-secret
        volumes:
            - shop-db:/var/lib/mysql
            
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1

volumes:
    shop-db:
    shop: